apps/company/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

#from . import views
#from django.conf.urls import url, include
from apps.company.views import *

app_name = 'company'
urlpatterns = [
    path('indexDriver', login_required(indexDriver), name='indexDriver'),
    path('createDriver', login_required(createDriver), name='createDriver'),
    re_path(r'^editDriver/(?P<id_driver>\d+)/$', login_required(editDriver), name='editDriver'),
    re_path(r'^deleteDriver/(?P<id_driver>\d+)/$', login_required(deleteDriver), name='deleteDriver'),
    path('indexBus', login_required(indexBus), name='indexBus'),
    path('createBus', login_required(createBus), name='createBus'),
    re_path(r'^editBus/(?P<id_bus>\d+)/$', login_required(editBus), name='editBus'),
    re_path(r'^deleteBus/(?P<id_bus>\d+)/$', login_required(deleteBus), name='deleteBus'),
]

apps/sales/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from apps.sales.views import *

app_name = 'sales'
urlpatterns = [
    path('viewMyRedirect', login_required(viewMyRedirect), name='viewMyRedirect'),
    path('indexPassenger', login_required(indexPassenger), name='indexPassenger'),
    path('createPassenger', login_required(createPassenger), name='createPassenger'),
    re_path(r'^editPassenger/(?P<id_passenger>\d+)/$', login_required(editPassenger), name='editPassenger'),
    re_path(r'^deletePassenger/(?P<id_passenger>\d+)/$', login_required(deletePassenger), name='deletePassenger'),
    path('indexJourney', login_required(indexJourney), name='indexJourney'),
    path('averageJourney', login_required(averageJourney), name='averageJourney'),
    path('createJourney', login_required(createJourney), name='createJourney'),
    re_path(r'^editJourney/(?P<id_journey>\d+)/$', login_required(editJourney), name='editJourney'),
    re_path(r'^deleteJourney/(?P<id_journey>\d+)/$', login_required(deleteJourney), name='deleteJourney'),
    re_path(r'^addBusJourney/(?P<id_journey>\d+)/$', login_required(addBusJourney), name='addBusJourney'),
    path('viewJourneys', login_required(viewJourneys), name='viewJourneys'),
    re_path(r'^buyTicket/(?P<id_trip>\d+)/$', login_required(buyTicket), name='buyTicket'),
    path('indexTicket', login_required(indexTicket), name='indexTicket'),
    path('porcentageCapacity', login_required(porcentageCapacity), name='porcentageCapacity'),
]

busCompany/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include

urlpatterns = [
    path('sales/', include('apps.sales.urls')),
    path('company/', include('apps.company.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<title>
			{% block title %}
				Document
			{% endblock %}
		</title>
		{% block cssFiles %}
		{% endblock %}
		<!--Import Google Icon Font-->
      	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      	<!--Import css from materialize-->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<style type="text/css">
			body {display: flex;min-height: 100vh;flex-direction: column;}
			main {flex: 1 0 auto;}
		</style>
		<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	</head>
	<body>
	{% block header %}
		{% include "base/header.html" %}
	{% endblock %}
	<div class="row">
		<div class="col s12">
			{% block titulo %}
			{% endblock titulo %}
		</div>
	</div>
	<main>
		<div style="margin-top:30px;">
			{% block content %}

			{% endblock %}
		</div>
	</main>
	{% block footer %}
		{% include "base/footer.html" %}
	{% endblock  %}
	<!--Import js from JQuery -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<!-- Import js from materilize -->
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
	{% block jsFiles %}
	{% endblock %}
	</body>
</html>

templates/base/footer.html
<footer class="main-footer">
  <div class="pull-right hidden-xs">
      <strong>Copyright&copy; 2019. Sitio desarrollado por <a href="https://www.linkedin.com/in/hgalvez-neculman">Hernán Gálvez Neculman</a>.</strong> Todos los derechos reservados.<b>Version</b> 1.0
  </div>
</footer>

templates/base/header.html
<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
		<a class="navbar-brand" href="#">Bus Company</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
				aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarColor01">
			<ul class="navbar-nav mr-auto">
				{% if user.is_superuser == True %}
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'sales:indexJourney' %}">Planifica</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'company:indexDriver' %}">Choferes</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'company:indexBus' %}">Buses</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'sales:indexTicket' %}">Ventas</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'sales:averageJourney' %}">Ventas por Trayecto</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'sales:porcentageCapacity' %}">Capacidad Vendida</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'sales:viewJourneys' %}">Comprar un Pasaje!</a>
				</li>
				{% endif %}
			</ul>
			<ul class="navbar-nav navbar-right">
				<li class="nav-item">
					<a class="nav-link" href="#">Bienvenido, {{ user.username }}!</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">Salir</a>
				</li>
			</ul>
		</div>
	</nav>
</header>