apps/sales/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path
from apps.sales.views import *

app_name = 'sales'
urlpatterns = [
    path('viewMyRedirect', login_required(viewMyRedirect), name='viewMyRedirect'),
    path('indexPassenger', login_required(indexPassenger), name='indexPassenger'),
    path('createPassenger', login_required(createPassenger), name='createPassenger'),
    re_path(r'^editPassenger/(?P<id_passenger>\d+)/$', login_required(editPassenger), name='editPassenger'),
    re_path(r'^deletePassenger/(?P<id_passenger>\d+)/$', login_required(deletePassenger), name='deletePassenger'),
    path('indexJourney', login_required(indexJourney), name='indexJourney'),
    path('averageJourney', login_required(averageJourney), name='averageJourney'),
    path('createJourney', login_required(createJourney), name='createJourney'),
    re_path(r'^editJourney/(?P<id_journey>\d+)/$', login_required(editJourney), name='editJourney'),
    re_path(r'^deleteJourney/(?P<id_journey>\d+)/$', login_required(deleteJourney), name='deleteJourney'),
    re_path(r'^addBusJourney/(?P<id_journey>\d+)/$', login_required(addBusJourney), name='addBusJourney'),
    path('viewJourneys', login_required(viewJourneys), name='viewJourneys'),
    re_path(r'^buyTicket/(?P<id_trip>\d+)/$', login_required(buyTicket), name='buyTicket'),
    path('indexTicket', login_required(indexTicket), name='indexTicket'),
    path('porcentageCapacity', login_required(porcentageCapacity), name='porcentageCapacity'),
]

busCompany/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include

urlpatterns = [
    path('sales/', include('apps.sales.urls')),
    path('company/', include('apps.company.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
]

apps/sales/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from apps.company.models import Bus


class Schedule(models.Model):
    hour = models.CharField(max_length=15)

    def __str__(self):
        return '{}'.format(self.hour)


class Journey(models.Model):
    states = (
        ('0', 'Inactivo'),
        ('1', 'Activo'),
    )
    origin = models.CharField(max_length=20)
    destination = models.CharField(max_length=20)
    schedule = models.ForeignKey(Schedule, null=True, blank=True, default=None, on_delete=models.PROTECT)
    date = models.DateField()
    state = models.CharField(max_length=20, default=1, choices=states)

    def __str__(self):
        return '{}-{}'.format(self.origin, self.destination)


class Passenger(models.Model):
    rut = models.CharField(max_length=10)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)


class Trip(models.Model):
    bus = models.ForeignKey(Bus, null=True, blank=True, default=None, on_delete=models.DO_NOTHING)
    journey = models.ForeignKey(Journey, null=True, blank=True, default=None, on_delete=models.DO_NOTHING)


class Ticket(models.Model):
    seats = (
        ('1', 'N° 1'),
        ('2', 'N° 2'),
        ('3', 'N° 3'),
        ('4', 'N° 4'),
        ('5', 'N° 5'),
        ('6', 'N° 6'),
        ('7', 'N° 7'),
        ('8', 'N° 8'),
        ('9', 'N° 9'),
        ('10', 'N° 10')
    )
    numSeat = models.CharField(max_length=20, default=1, choices=seats)
    trip = models.ForeignKey(Trip, null=True, blank=True, default=None, on_delete=models.PROTECT)
    passenger = models.ForeignKey(User, null=True, blank=True, default=None, on_delete=models.PROTECT)

    def __str__(self):
        return '{}-{}: {}'.format(self.numSeat, self.trip, self.passenger)

apps/sales/views.py
from django.contrib.auth.models import User
from django.db.models import Sum, Count, F
from django.shortcuts import render, redirect

from apps.company.models import Bus
from apps.sales.form import passengerForm, journeyForm, addBusForm, buyTicketForm
from apps.sales.models import Passenger, Journey, Trip, Ticket


# Create your views here.
def indexPassenger(request):
    passengers = Passenger.objects.all()

    return render(request, "sales/indexPassenger.html", {'passengers': passengers})


def createPassenger(request):
    form = passengerForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('sales:indexPassenger')

    return render(request, 'sales/createPassenger.html', {'form': form})


def editPassenger(request, id_passenger):
    passenger = Passenger.objects.get(id=id_passenger)
    if request.method == 'GET':
        form = passengerForm(instance=passenger)
    else:
        form = passengerForm(request.POST, instance=passenger)
        if form.is_valid():
            form.save()
        return redirect('sales:indexPassenger')
    return render(request, 'sales/createPassenger.html', {'form': form})


def deletePassenger(request, id_passenger):
    passenger = Passenger.objects.get(id=id_passenger)
    if request.method == 'POST':
        passenger.delete()
        return redirect('sales:indexPassenger')
    return render(request, 'sales/deletePassenger.html', {'passenger': passenger})


def indexJourney(request):
    journeys = Journey.objects.all()

    return render(request, "sales/indexJourney.html", {'journeys': journeys})

def averageJourney(request):

    journeys = Ticket.objects.filter(trip__journey__state='1').values('trip', 'trip__journey').annotate(pasajes=Count('trip'))

    journeys = journeys.values('trip__journey', 'pasajes').annotate(Count('trip'), origen=F('trip__journey__origin'), destino=F('trip__journey__destination'))

    return render(request, "sales/averageJourney.html", {'journeys': journeys})


def viewJourneys(request):
    trips = Trip.objects.filter(journey__state='1')

    return render(request, "sales/viewJourneys.html", {'trips': trips})


def viewMyRedirect(request):
    if request.user.is_superuser:
        return redirect('sales:indexJourney')
    else:
        return redirect('sales:viewJourneys')

def createJourney(request):

    if request.method == 'POST':
        form = journeyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('sales:indexJourney')
    else:
        form = journeyForm()

    return render(request, 'sales/createJourney.html', {'form': form})


def editJourney(request, id_journey):
    journey = Journey.objects.get(id=id_journey)
    if request.method == 'GET':
        form = journeyForm(instance=journey)
    else:
        form = journeyForm(request.POST, instance=journey)
        if form.is_valid():
            form.save()
        return redirect('sales:indexJourney')
    return render(request, 'sales/createJourney.html', {'form': form})


def deleteJourney(request, id_journey):
    journey = Journey.objects.get(id=id_journey)
    if request.method == 'POST':
        journey.state = 0
        journey.save()
        return redirect('sales:indexJourney')
    return render(request, 'sales/deleteJourney.html', {'journey': journey})


def addBusJourney(request, id_journey):
    journey = Journey.objects.get(id=id_journey)

    if request.method == 'POST':
        form = addBusForm(request.POST)
        if form.is_valid():
            search_trip = Trip.objects.filter(bus=request.POST['bus'], journey=request.POST['journey'])
            if search_trip.count() != 0:
                pass
            else:
                form.save()
        return redirect('sales:indexJourney')
    else:
        form = addBusForm()
        form.fields['journey'].initial = journey
        form.fields['journey'].widget.attrs['style'] = 'display:none'

    return render(request, 'sales/addBusJourney.html', {'form': form, 'journey': journey})


def buyTicket(request, id_trip):
    trip = Trip.objects.get(id=id_trip)

    form = buyTicketForm(request.POST or None)

    if request.method == 'POST':
        search_seat = Ticket.objects.filter(trip=request.POST['trip'], numSeat=request.POST['numSeat'])
        if search_seat.count() != 0:
            form.add_error('numSeat', 'Este asiento ya se encuentra ocupado.')
        else:
            search_ticket = Ticket.objects.filter(trip=request.POST['trip'], passenger=request.POST['passenger'])

            if search_ticket.count() != 0:
                form.add_error('numSeat', 'El pasajero ya ha comprado un pasaje en este viaje.')
            if form.is_valid():
                form.save()
                return redirect('sales:viewJourneys')
    else:
        form.fields['trip'].initial = trip
        form.fields['passenger'].initial = request.user.id

    form.fields['trip'].widget.attrs['style'] = 'display:none'
    form.fields['passenger'].widget.attrs['style'] = 'display:none'

    return render(request, 'sales/buyTicket.html', {'form': form, 'trip': trip})


def indexTicket(request):
    tickets = Ticket.objects.all()

    return render(request, "sales/indexTicket.html", {'tickets': tickets})


def porcentageCapacity(request):
    journeys = Journey.objects.filter(state='1').values('origin', 'destination')
    buses = None

    if request.method == 'POST':
        origen, destino = str(request.POST['journey']).split('-')
        porcent = str(request.POST['porcent'])
        print(origen, destino, porcent)

        buses = Ticket.objects.filter(trip__journey__origin=origen,
                                      trip__journey__destination=destino).\
            values('trip', 'trip__bus__license').annotate(
            pasajes=Count('trip'),
            chofer=F('trip__bus__driver__name')).annotate(percent=F('pasajes')*10).filter(percent__gte=porcent)
        print(buses)

    return render(request, 'sales/porcentageCapacity.html', {'journeys': journeys, 'buses': buses})

templates/sales/addBusJourney.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Asignar Bus</legend>
                <h1>¿Desea asignar un bus para {{ journey.origin }}-{{ journey.destination }}?</h1>
                <div class="form-group row">
                  <div class="col-sm-10">
                    {{ form.journey }}
                  </div>
                </div>
                <div class="form-group row">
                  <label for="staticRut" class="col-sm-2 col-form-label">Asignar Bus</label>
                  <div class="col-sm-10">
                    {{ form.bus }}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a class="btn btn-default btn-sm" href="{% url 'sales:indexJourney' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/sales/averageJourney.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3> Promedios de ventas </h3>
        <table id="table" class="table" >
            <thead>
                <th>Origen</th>
                <th>Destino</th>
                <th>Total de pasajes vendidos</th>
            </thead>
            <tbody>
                {% for journey in journeys %}
                <tr>
                    <td>{{ journey.origen }}</td>
                    <td>{{ journey.destino }}</td>
                    <td>{{ journey.pasajes }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/sales/buyTicket.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Comprar Ticket</legend>
                <h3>¿Desea comprar un ticket para el destino {{ trip.journey.origin }}-{{ trip.journey.destination }}?</h3>
                <div class="form-group row">
                    <div class="col-sm-10">
                        {{ form.numSeat }}
                    </div>
                    <div class="col-sm-10">
                        {{ form.trip }}
                    </div>
                    <div class="col-sm-10">
                        {{ form.passenger }}
                    </div>
                </div>
                {{ form.errors }}
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a class="btn btn-default btn-sm" href="{% url 'sales:viewJourneys' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/sales/createJourney.html
{% extends "base/base.html" %}
{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        <fieldset>
            <legend>Trayecto</legend>
            <div class="form-group row">
                <label for="staticOrigin" class="col-sm-2 col-form-label">Origen</label>
                <div class="col-sm-10">
                    {{ form.origin }}
                </div>
            </div>
            <div class="form-group row">
                <label for="staticDestination" class="col-sm-2 col-form-label">Destino</label>
                <div class="col-sm-10">
                    {{ form.destination }}
                </div>
            </div>
            <div class="form-group row">
                <label for="staticDate" class="col-sm-2 col-form-label">Fecha</label>
                <div class="col-sm-10">
                    {{ form.date }}
                    {{ form.date.errors }}
                </div>
            </div>
            <div class="form-group row">
                <label for="staticHour" class="col-sm-2 col-form-label">Hora</label>
                <div class="col-sm-10">
                    {{ form.schedule }}
                </div>
            </div>
            <div class="form-group row">
                <label for="staticState" class="col-sm-2 col-form-label">Estado</label>
                <div class="col-sm-10">
                    {{ form.state }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
            <a class="btn btn-warning btn-sm" href="{% url 'sales:indexJourney' %}">Volver</a>
        </fieldset>
    </form>
</div>
{% endblock  %}

templates/sales/createPassenger.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Pasajero</legend>
                <div class="form-group row">
                  <label for="staticName" class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-10">
                    {{ form.name }}
                  </div>
                </div>
                <div class="form-group row">
                  <label for="staticRut" class="col-sm-2 col-form-label">Rut</label>
                  <div class="col-sm-10">
                    {{ form.rut }}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a class="btn btn-warning btn-sm" href="{% url 'sales:indexPassenger' %}">Volver</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/sales/deleteJourney.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Eliminar pasajero</legend>
                <h1>¿Desea eliminar este destino {{ journey.origin }}-{{ journey.destination }}?</h1>
                <button type="submit" class="btn btn-danger btn-sm">Sí, eliminar</button>
                <a class="btn btn-default btn-sm" href="{% url 'sales:indexJourney' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/sales/deletePassenger.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Eliminar pasajero</legend>
                <h1>¿Desea eliminar el pasajero {{ passenger.name }}?</h1>
                <button type="submit" class="btn btn-danger btn-sm">Sí, eliminar</button>
                <a class="btn btn-default btn-sm" href="{% url 'sales:indexPassenger' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/sales/indexJourney.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3>Trayectos <a href="/sales/createJourney" class="btn btn-primary btn-sm">Agregar</a></h3>
        <table id="table" class="table" >
            <thead>
                <th>Origen</th>
                <th>Destino</th>
                <th>Horario</th>
                <th>Fecha</th>
                <th>Acciones</th>
            </thead>
            <tbody>
                {% for journey in journeys %}
                <tr>
                    <td>{{ journey.origin }}</td>
                    <td>{{ journey.destination }}</td>
                    <td>{{ journey.schedule }} Hrs.</td>
                    <td>{{ journey.date }}</td>
                    <td>
                        {% if journey.state == '1' %}
                        <a href="{% url 'sales:deleteJourney' journey.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        <a href="{% url 'sales:editJourney' journey.id %}" class="btn btn-info btn-sm">Editar</a>
                        <a href="{% url 'sales:addBusJourney' journey.id %}" class="btn btn-warning btn-sm">Asignar Bus</a>
                        {% else %}
                        <a href="{% url 'sales:editJourney' journey.id %}" class="btn btn-success btn-sm">Habilitar</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/sales/indexPassenger.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3>Pasajeros <a href="/sales/createPassenger" class="btn btn-primary btn-sm">Agregar</a></h3>
        <table id="table" class="table" >
            <thead>
                <th>Nombre</th>
                <th>Rut</th>
                <th>Acciones</th>
            </thead>
            <tbody>
                {% for passenger in passengers %}
                <tr>
                    <td>{{ passenger.name }}</td>
                    <td>{{ passenger.rut }}</td>
                    <td>
                        <a href="{% url 'sales:deletePassenger' passenger.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        <a href="{% url 'sales:editPassenger' passenger.id %}" class="btn btn-info btn-sm">Editar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/sales/indexTicket.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3>Ticket Vendidos </h3>
        <table id="table" class="table" >
            <thead>
                <th>Destino</th>
                <th>Pasajero</th>
                <th>Numero Asiento</th>
            </thead>
            <tbody>
                {% for ticket in tickets %}
                <tr>
                    <td>{{ ticket.trip.journey }}</td>
                    <td>{{ ticket.passenger }}</td>
                    <td>{{ticket.numSeat }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/sales/viewJourneys.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3> Trayectos Disponibles </h3>
        <table id="table" class="table" >
            <thead>
                <th>Origen</th>
                <th>Destino</th>
                <th>Horario</th>
                <th>Fecha</th>
                <th>Bus Asignado</th>
                <th>Acciones</th>
            </thead>
            <tbody>
                {% for trip in trips %}
                <tr>
                    <td>{{ trip.journey.origin }}</td>
                    <td>{{ trip.journey.destination }}</td>
                    <td>{{ trip.journey.schedule }} Hrs.</td>
                    <td>{{ trip.journey.date }}</td>
                    <td>{{ trip.bus }}</td>
                    <td>
                        <a href="{% url 'sales:buyTicket' trip.id %}" class="btn btn-success btn-sm">Comprar Pasaje</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}