apps/company/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, re_path

#from . import views
#from django.conf.urls import url, include
from apps.company.views import *

app_name = 'company'
urlpatterns = [
    path('indexDriver', login_required(indexDriver), name='indexDriver'),
    path('createDriver', login_required(createDriver), name='createDriver'),
    re_path(r'^editDriver/(?P<id_driver>\d+)/$', login_required(editDriver), name='editDriver'),
    re_path(r'^deleteDriver/(?P<id_driver>\d+)/$', login_required(deleteDriver), name='deleteDriver'),
    path('indexBus', login_required(indexBus), name='indexBus'),
    path('createBus', login_required(createBus), name='createBus'),
    re_path(r'^editBus/(?P<id_bus>\d+)/$', login_required(editBus), name='editBus'),
    re_path(r'^deleteBus/(?P<id_bus>\d+)/$', login_required(deleteBus), name='deleteBus'),
]

busCompany/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include

urlpatterns = [
    path('sales/', include('apps.sales.urls')),
    path('company/', include('apps.company.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
]

apps/company/models.py
from django.db import models

# Create your models here.


class Driver(models.Model):
    rut = models.CharField(max_length=10)
    name = models.CharField(max_length=50)

    def __str__(self):
        return '{}'.format(self.name)


class Bus(models.Model):
    driver = models.ForeignKey(Driver, null=True, blank=True, default=None, on_delete=models.PROTECT)
    license = models.CharField(max_length=6)

    def __str__(self):
        return '{}'.format(self.license)

apps/company/forms.py
from django import forms

from apps.company.models import Driver, Bus


class driverForm(forms.ModelForm):
    class Meta:
        model = Driver
        fields = [
                 'name',
                 'rut'
        ]
        label = {
                'name': 'Nombre',
                'rut': 'Rut',
        }
        widget = {
                'name': forms.TextInput(attrs={'class': 'form-control'}),
                'rut': forms.TextInput(attrs={'class': 'form-control'}),
        }


class busForm(forms.ModelForm):
    class Meta:
        model = Bus
        fields = [
            'driver',
            'license'
        ]
        label = {
            'driver': 'Chofer',
            'license': 'Patente',
        }
        widget = {
            'driver': forms.Select(attrs={'class': 'form-control'}),
            'license': forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/company/views.py
from django.shortcuts import render, redirect
from apps.company.forms import driverForm, busForm
from apps.company.models import Driver, Bus


# Create your views here.
def indexDriver(request):
    drivers = Driver.objects.all()

    return render(request, "company/indexDriver.html", {'drivers': drivers})


def createDriver(request):
    form = driverForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('company:indexDriver')

    return render(request, 'company/createDriver.html', {'form': form})


def editDriver(request, id_driver):
    driver = Driver.objects.get(id=id_driver)
    if request.method == 'GET':
        form = driverForm(instance=driver)
    else:
        form = driverForm(request.POST, instance=driver)
        if form.is_valid():
            form.save()
        return redirect('company:indexDriver')
    return render(request, 'company/createDriver.html', {'form': form})


def deleteDriver(request, id_driver):
    driver = Driver.objects.get(id=id_driver)
    if request.method == 'POST':
        driver.delete()
        return redirect('company:indexDriver')
    return render(request, 'company/deleteDriver.html', {'driver': driver})


def indexBus(request):
    buses = Bus.objects.all()

    return render(request, "company/indexBus.html", {'buses': buses})


def createBus(request):
    form = busForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
        return redirect('company:indexBus')

    return render(request, 'company/createBus.html', {'form': form})


def editBus(request, id_bus):
    bus = Bus.objects.get(id=id_bus)
    if request.method == 'GET':
        form = busForm(instance=bus)
    else:
        form = busForm(request.POST, instance=bus)
        if form.is_valid():
            form.save()
        return redirect('company:indexBus')
    return render(request, 'company/createBus.html', {'form': form})


def deleteBus(request, id_bus):
    bus = Bus.objects.get(id=id_bus)
    if request.method == 'POST':
        bus.delete()
        return redirect('company:indexBus')
    return render(request, 'company/deleteBus.html', {'bus': bus})

templates/company/createBus.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Crear nuevo bus</legend>
                <div class="form-group row">
                  <label for="staticName" class="col-sm-2 col-form-label">Asignar Chofer</label>
                  <div class="col-sm-10">
                    {{ form.driver }}
                  </div>
                </div>
                <div class="form-group row">
                  <label for="staticRut" class="col-sm-2 col-form-label">Placa Patente</label>
                  <div class="col-sm-10">
                    {{ form.license }}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a class="btn btn-warning btn-sm" href="{% url 'company:indexBus' %}">Volver</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/company/createDriver.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Crear nuevo chofer</legend>
                <div class="form-group row">
                  <label for="staticName" class="col-sm-2 col-form-label">Nombre</label>
                  <div class="col-sm-10">
                    {{ form.name }}
                  </div>
                </div>
                <div class="form-group row">
                  <label for="staticRut" class="col-sm-2 col-form-label">Rut</label>
                  <div class="col-sm-10">
                    {{ form.rut }}
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a class="btn btn-warning btn-sm" href="{% url 'company:indexDriver' %}">Volver</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/company/deleteBus.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Eliminar bus</legend>
                <h1>¿Desea eliminar el bus con matrícula: {{ bus.license }}?</h1>
                <button type="submit" class="btn btn-danger btn-sm">Sí, eliminar</button>
                <a class="btn btn-default btn-sm" href="{% url 'company:indexBus' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/company/deleteDriver.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Eliminar chofer</legend>
                <h1>¿Desea eliminar el chofer {{ driver.name }}?</h1>
                <button type="submit" class="btn btn-danger btn-sm">Sí, eliminar</button>
                <a class="btn btn-default btn-sm" href="{% url 'company:indexDriver' %}">Cancelar</a>
            </fieldset>
        </form>
    </div>
{% endblock  %}

templates/company/indexBus.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3>Buses <a href="/company/createBus" class="btn btn-primary btn-sm">Agregar</a></h3>
        <table id="table" class="table" >
            <thead>
                <th>Chofer Asignado</th>
                <th>Placa Patente</th>
                <th>Acciones</th>
            </thead>
            <tbody>
                {% for bus in buses %}
                <tr>
                    <td>{{ bus.driver }}</td>
                    <td>{{ bus.license }}</td>
                    <td>
                        <a href="{% url 'company:deleteBus' bus.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        <a href="{% url 'company:editBus' bus.id %}" class="btn btn-info btn-sm">Editar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}

templates/company/indexDriver.html
{% extends "base/base.html" %}
{% block content %}
    <div class="container" >
        <h3>Choferes <a href="/company/createDriver" class="btn btn-primary btn-sm">Agregar</a></h3>
        <table id="table" class="table" >
            <thead>
                <th>Nombre</th>
                <th>Rut</th>
                <th>Acciones</th>
            </thead>
            <tbody>
                {% for driver in drivers %}
                <tr>
                    <td>{{ driver.name }}</td>
                    <td>{{ driver.rut }}</td>
                    <td>
                        <a href="{% url 'company:deleteDriver' driver.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        <a href="{% url 'company:editDriver' driver.id %}" class="btn btn-info btn-sm">Editar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}
{% block jsFiles %}
    <script>
        var table;
        $(document).ready(function () {
            table = $("#table").DataTable({
                "responsive": true,
                "order": [0, 'asc'],
                "paging": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "columnDefs": [
                        { targets: 'no-sort', orderable: false }
                    ],
                "language": {
                    "sProcessing":     "Procesando...",
                    "sLengthMenu":     "Mostrar _MENU_ registros",
                    "sZeroRecords":    "No se encontraron resultados",
                    "sEmptyTable":     "Ningún dato disponible en esta tabla",
                    "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix":    "",
                    "sSearch":         "Buscar:",
                    "sUrl":            "",
                    "sInfoThousands":  ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst":    "Primero",
                        "sLast":     "Último",
                        "sNext":     "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                },
            });
        });
    </script>
{% endblock %}