apps/user/urls.py
from django.urls import path
from apps.user.views import *

app_name = 'user'
urlpatterns = [
    path('registryUser', registryUser.as_view(), name='registryUser'),
]

busCompany/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, logout_then_login
from django.urls import path, include

urlpatterns = [
    path('sales/', include('apps.sales.urls')),
    path('company/', include('apps.company.urls')),
    path('user/', include('apps.user.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='index.html'), name="login"),
    path('logout/', logout_then_login, name="logout"),
]

templates/index.html
{% extends "base/base.html" %}
{% load static %}
{% block tittle %}
Ingresar
{% endblock %}
{% block header %}

{% endblock header %}

{% block content %}

<style>
    main{
        background-image:url("{% static "images/bus.jpg" %}");
        background-repeat:round;
    }
</style>

<div>
    <div class="col-md-6 offset-md-3" style="margin-top:100px;">
        <div class="card border-warning mb-3">
            <form method="post">
                {% csrf_token %}
                <fieldset>
                    <div class="card-header">Ingreso de Usuarios</div>
                    <div class="card-body">
                        <div class="container">
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Nombre usuario</label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" name="username">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-4 col-form-label">Contraseña</label>
                                <div class="col-sm-8">
                                    <input type="password" class="form-control" name="password">
                                </div>
                            </div>
                        </div>
                        <div class="container">
                            <div class="form-group row">
                                <div class="col-sm-6">
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-outline-success btn-sm btn-block">Ingresar
                                        </button>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="text-center">
                                        <a class="btn btn-outline-info btn-sm btn-block"
                                           href="{% url 'user:registryUser' %}">Registrarme</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
{% endblock  %}

{% block footer %}

{% endblock footer %}